/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulespat;

import basic.utils;
import basic.Config;
import basic.SendEmail;
import basic.WiderCombo;
import basic.global;
import basic.utils;
import basic.ComboBoxCellEditor;
import basic.FillCombo;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oski
 */
public class dEquipmentControl extends javax.swing.JDialog {

    /**
     * Creates new form dEquipmentControl
     */
    DefaultTableModel equipmentctrl;
    boolean banderaConsulta;
    public dEquipmentControl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         equipmentctrl = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            equipmentctrl.addColumn("equipo");
            equipmentctrl.addColumn("tam.");

            equipmentctrl.addColumn("ubicacion");
            //equipmentctrl.addColumn("despacho");
            equipmentctrl.addColumn("fecha despacho");
            equipmentctrl.addColumn("hora depacho");
            equipmentctrl.addColumn("dias despacho");
            equipmentctrl.addColumn("carga despacho.");
            equipmentctrl.addColumn("cliente despacho");
            equipmentctrl.addColumn("ingreso patio");
            equipmentctrl.addColumn("ubicacion patio");
            equipmentctrl.addColumn("fecha patio");
            equipmentctrl.addColumn("hora patio");
            equipmentctrl.addColumn("dias patio");

            equipmentctrl.addColumn("carga patio");
            equipmentctrl.addColumn("cliente patio");
            equipmentctrl.addColumn("seals.");
            equipmentctrl.addColumn("celula distribuicion.");
            equipmentctrl.addColumn("comentarios");
            equipmentctrl.addColumn("fecha taller");
            equipmentctrl.addColumn("dias taller");

            CTRL.setModel(equipmentctrl);
            
            actualizarListado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        filtroEquiTxt = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        filtroBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        CTRL = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 550));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setMinimumSize(new java.awt.Dimension(909, 40));
        jPanel31.setPreferredSize(new java.awt.Dimension(909, 50));
        jPanel31.setLayout(null);

        filtroEquiTxt.setMinimumSize(new java.awt.Dimension(40, 20));
        filtroEquiTxt.setName(""); // NOI18N
        filtroEquiTxt.setPreferredSize(new java.awt.Dimension(200, 20));
        filtroEquiTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroEquiTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroEquiTxtKeyReleased(evt);
            }
        });
        jPanel31.add(filtroEquiTxt);
        filtroEquiTxt.setBounds(10, 10, 220, 20);

        jButton19.setText("Actualizar listado");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel31.add(jButton19);
        jButton19.setBounds(810, 10, 129, 25);

        jButton20.setText("Exportar a documento de excel");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel31.add(jButton20);
        jButton20.setBounds(930, 10, 209, 25);

        filtroBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Equipo", "Ubicacion", "Cliente" }));
        filtroBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroBoxItemStateChanged(evt);
            }
        });
        jPanel31.add(filtroBox);
        filtroBox.setBounds(250, 10, 200, 22);

        jPanel1.add(jPanel31, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(1280, 500));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1280, 500));

        CTRL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CTRL.setMinimumSize(new java.awt.Dimension(900, 390));
        CTRL.setPreferredSize(new java.awt.Dimension(900, 390));
        jScrollPane3.setViewportView(CTRL);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void actualizarListado() { 

        int filtro = filtroBox.getSelectedIndex();
        String filtroEquipo = "", filtroUbi = "", filtroCliente = "";
        if (filtro > 0 && !filtroEquiTxt.getText().toString().isEmpty()) {
            banderaConsulta = true;
            if (filtro == 1) {
                filtroEquipo = " where NoEconomico LIKE '%" + filtroEquiTxt.getText().toString() + "%'";
            } else if (filtro == 2) {
                filtroUbi = " where getUbicacionDespachoPatios(TBL.NoEconomico) LIKE '%" + filtroEquiTxt.getText().toString() + "%'";
            } else {
                filtroCliente = " where getClienteDespachoPatios(TBL.NoEconomico) LIKE '%" + filtroEquiTxt.getText().toString() + "%'";
            }
        }
//      if(banderaConsulta){
//          banderaConsulta = false;
 System.out.println("SELECT\n"
                    + "    IFNULL(Noeconomico, '-') AS equipo,\n"
                    + "    IFNULL(tamano, '') AS tamano,\n"
                    + "    IF((SELECT tamano) = '', '-', (SELECT tamano)) AS tamanox,\n"
                    + "    NOW() AS hoy,\n"
                    + "    getUbicacionDespachoPatios(TBL.noeconomico) AS ubicacionD,\n"
                    + "    DATE_FORMAT(FechaD, '%m/%d/%Y') AS FechaDx,\n"
                    + "    DATE_FORMAT(FechaD, '%H:%i') AS HoraD,\n"
                    + "    IFNULL((SELECT DATEDIFF(NOW(), (SELECT FechaD)) + 1), '') AS diasD,\n"
                    + "    getCargaDespachoPatios(TBL.noeconomico) AS cargaD,\n"
                    + "    clienteD,\n"
                    + "    IFNULL((SELECT Sello FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '') AS sellos,\n"
                    + "    IF((SELECT sellos) = '', '-', (SELECT sellos)) AS sellox,\n"
                    + "    IFNULL((SELECT DATE_FORMAT(FechaEvento, '%m/%d/%Y') FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS fechax,\n"
                    + "    IFNULL((SELECT DATE_FORMAT(fechaevento, '%H:%i') FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS fechaxhora,\n"
                    + "    IF(ubicacionpatio != '' OR ubicacionpatio IS NOT NULL, 'IN', '-') AS ingresopatio,\n"
                    + "    IF(ubicacionpatio != '' OR ubicacionpatio IS NOT NULL, ubicacionpatio, '-') AS ubicacionpatio,\n"
                    + "    IFNULL((SELECT IF(EstadoCarga = 0, 'E', 'L') FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS carga,\n"
                    + "    IFNULL((SELECT nombre FROM unidadnegocio_tbl WHERE `UnidadID` = unegocioID), '-') AS unidad_negocio,\n"
                    + "    IF((SELECT unidad_negocio) = '', '-', (SELECT unidad_negocio)) AS unidad_negociox,\n"
                    + "    IFNULL((SELECT DATEDIFF(NOW(), (SELECT fechaevento FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1)) + 1), '-') AS dias,\n"
                    + "    IFNULL((SELECT ncomercial FROM clientes_tbl WHERE clienteID = ((SELECT clienteID FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1))), '-') AS cliente,\n"
                    + "    IF((SELECT cliente) = '', '-', (SELECT cliente)) AS clienteX,\n"
                    + "    IFNULL((SELECT nota FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS comment,\n"
                    + "    IF((SELECT comment) = '', '-', (SELECT comment)) AS commentx,\n"
                    + "    IFNULL(DATE_FORMAT((SELECT fecha FROM requimant_tbl WHERE camionID = cajaID AND categoriaID = 2 AND STATUS > 0 AND (STATUS != 4 OR STATUS != 5)\n"
                    + "            ORDER BY requisicionID DESC LIMIT 1), '%m/%d/%Y'), '-') AS Ultima_Entrada_Taller,\n"
                    + "    IF((SELECT Ultima_Entrada_Taller) = '', '-', (SELECT Ultima_Entrada_Taller)) AS Ultima_Entrada_Tallerx,\n"
                    + "    IFNULL((SELECT DATEDIFF(NOW(), fecha) FROM requimant_tbl WHERE camionID = cajaID AND categoriaID = 2 AND STATUS > 0 AND (STATUS != 4 OR STATUS != 5)\n"
                    + "            ORDER BY requisicionID DESC LIMIT 1), '') AS Dias_Taller,\n"
                    + "    IF((SELECT Dias_Taller) = '', '-', (SELECT Dias_Taller)) AS Dias_Tallerx,\n"
                    + "    IFNULL((SELECT dias + 0), 0) AS diax,\n"
                    + "    (SELECT 0) AS Zero,\n"
                    + "    (SELECT 6) AS Six,\n"
                    + "    (SELECT 10) AS Ten\n"
                    + "FROM\n"
                    + "    (SELECT *,\n"
                    + "            (SELECT inventarioID FROM inventarioexterno_tbl WHERE contenedor = cajas_tbl.`NoEconomico` ORDER BY inventarioID DESC LIMIT 1) AS inventarioID,\n"
                    + "            getFechaDespachoPatios(noeconomico) AS FechaD,\n"
                    + "            IFNULL(getClienteDespachoPatios(noeconomico), '-') AS clienteD,\n"
                    + "            (SELECT (SELECT nombre FROM patios_tbl WHERE patioID = inventarioexterno_tbl.`PatioID`) FROM inventarioexterno_tbl WHERE contenedor = noeconomico AND (SELECT anteriorID FROM inventarioexterno_tbl AS w WHERE anteriorID = inventarioexterno_tbl.InventarioID LIMIT 1) IS NULL AND TipoEvento = 1 ORDER BY inventarioID DESC LIMIT 1) AS ubicacionpatio\n"
                    + "     FROM\n"
                    + "        cajas_tbl\n"
                    + "     WHERE\n"
                    + "        STATUS IS TRUE) TBL\n"
                    + "    "+filtroCliente+" "+filtroUbi+"  "+filtroEquipo+" \n"
                    + "ORDER BY\n"
                    + "    (SELECT diax) DESC;");
        equipmentctrl.setRowCount(0);

        Connection con;
        con = utils.startConnection();

        try {
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery("SELECT\n"
                    + "    IFNULL(Noeconomico, '-') AS equipo,\n"
                    + "    IFNULL(tamano, '') AS tamano,\n"
                    + "    IF((SELECT tamano) = '', '-', (SELECT tamano)) AS tamanox,\n"
                    + "    NOW() AS hoy,\n"
                    + "    getUbicacionDespachoPatios(TBL.noeconomico) AS ubicacionD,\n"
                    + "    DATE_FORMAT(FechaD, '%m/%d/%Y') AS FechaDx,\n"
                    + "    DATE_FORMAT(FechaD, '%H:%i') AS HoraD,\n"
                    + "    IFNULL((SELECT DATEDIFF(NOW(), (SELECT FechaD)) + 1), '') AS diasD,\n"
                    + "    getCargaDespachoPatios(TBL.noeconomico) AS cargaD,\n"
                    + "    clienteD,\n"
                    + "    IFNULL((SELECT Sello FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '') AS sellos,\n"
                    + "    IF((SELECT sellos) = '', '-', (SELECT sellos)) AS sellox,\n"
                    + "    IFNULL((SELECT DATE_FORMAT(FechaEvento, '%m/%d/%Y') FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS fechax,\n"
                    + "    IFNULL((SELECT DATE_FORMAT(fechaevento, '%H:%i') FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS fechaxhora,\n"
                    + "    IF(ubicacionpatio != '' OR ubicacionpatio IS NOT NULL, 'IN', '-') AS ingresopatio,\n"
                    + "    IF(ubicacionpatio != '' OR ubicacionpatio IS NOT NULL, ubicacionpatio, '-') AS ubicacionpatio,\n"
                    + "    IFNULL((SELECT IF(EstadoCarga = 0, 'E', 'L') FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS carga,\n"
                    + "    IFNULL((SELECT nombre FROM unidadnegocio_tbl WHERE `UnidadID` = unegocioID), '-') AS unidad_negocio,\n"
                    + "    IF((SELECT unidad_negocio) = '', '-', (SELECT unidad_negocio)) AS unidad_negociox,\n"
                    + "    IFNULL((SELECT DATEDIFF(NOW(), (SELECT fechaevento FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1)) + 1), '-') AS dias,\n"
                    + "    IFNULL((SELECT ncomercial FROM clientes_tbl WHERE clienteID = ((SELECT clienteID FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1))), '-') AS cliente,\n"
                    + "    IF((SELECT cliente) = '', '-', (SELECT cliente)) AS clienteX,\n"
                    + "    IFNULL((SELECT nota FROM inventarioexterno_tbl WHERE inventarioID = TBL.inventarioID LIMIT 1), '-') AS comment,\n"
                    + "    IF((SELECT comment) = '', '-', (SELECT comment)) AS commentx,\n"
                    + "    IFNULL(DATE_FORMAT((SELECT fecha FROM requimant_tbl WHERE camionID = cajaID AND categoriaID = 2 AND STATUS > 0 AND (STATUS != 4 OR STATUS != 5)\n"
                    + "            ORDER BY requisicionID DESC LIMIT 1), '%m/%d/%Y'), '-') AS Ultima_Entrada_Taller,\n"
                    + "    IF((SELECT Ultima_Entrada_Taller) = '', '-', (SELECT Ultima_Entrada_Taller)) AS Ultima_Entrada_Tallerx,\n"
                    + "    IFNULL((SELECT DATEDIFF(NOW(), fecha) FROM requimant_tbl WHERE camionID = cajaID AND categoriaID = 2 AND STATUS > 0 AND (STATUS != 4 OR STATUS != 5)\n"
                    + "            ORDER BY requisicionID DESC LIMIT 1), '') AS Dias_Taller,\n"
                    + "    IF((SELECT Dias_Taller) = '', '-', (SELECT Dias_Taller)) AS Dias_Tallerx,\n"
                    + "    IFNULL((SELECT dias + 0), 0) AS diax,\n"
                    + "    (SELECT 0) AS Zero,\n"
                    + "    (SELECT 6) AS Six,\n"
                    + "    (SELECT 10) AS Ten\n"
                    + "FROM\n"
                    + "    (SELECT *,\n"
                    + "            (SELECT inventarioID FROM inventarioexterno_tbl WHERE contenedor = cajas_tbl.`NoEconomico` ORDER BY inventarioID DESC LIMIT 1) AS inventarioID,\n"
                    + "            getFechaDespachoPatios(noeconomico) AS FechaD,\n"
                    + "            IFNULL(getClienteDespachoPatios(noeconomico), '-') AS clienteD,\n"
                    + "            (SELECT (SELECT nombre FROM patios_tbl WHERE patioID = inventarioexterno_tbl.`PatioID`) FROM inventarioexterno_tbl WHERE contenedor = noeconomico AND (SELECT anteriorID FROM inventarioexterno_tbl AS w WHERE anteriorID = inventarioexterno_tbl.InventarioID LIMIT 1) IS NULL AND TipoEvento = 1 ORDER BY inventarioID DESC LIMIT 1) AS ubicacionpatio\n"
                    + "     FROM\n"
                    + "        cajas_tbl\n"
                    + "     WHERE\n"
                    + "        STATUS IS TRUE limit 30) TBL\n"
                    + "    "+filtroCliente+" "+filtroUbi+"  "+filtroEquipo+" \n"
                    + "ORDER BY\n"
                    + "    (SELECT diax) DESC;");
            
           

            while (rs.next()) {

                equipmentctrl.addRow(new Object[]{
                    rs.getString("equipo"),
                    rs.getString("tamanox"),
                    rs.getString("ubicacionD"),
                    rs.getString("FechaDx"),
                    rs.getString("HoraD"),
                    rs.getString("diasD"),
                    rs.getString("cargaD"),
                    rs.getString("clienteD"),
                    //rs.getString("ubicacion"),
                    rs.getString("ingresopatio"),
                    rs.getString("ubicacionpatio"),
                    rs.getString("fechax"),
                    rs.getString("fechaxhora"),
                    rs.getString("dias"),
                    rs.getString("carga"),
                    rs.getString("clienteX"),
                    rs.getString("sellox"),
                    rs.getString("unidad_negociox"),
                    rs.getString("commentx"),
                    rs.getString("Ultima_Entrada_Tallerx"),
                    rs.getString("Dias_Tallerx"),});
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
//        }
    }
    private void filtroEquiTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroEquiTxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (filtroBox.getSelectedIndex() > 0) {
                actualizarListado();
            } else {
                JOptionPane.showMessageDialog(this, "Por favor selecciona un filtro", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_filtroEquiTxtKeyPressed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        actualizarListado();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        String ret = utils.exportTabletoExcel(this, CTRL);
        if (!ret.isEmpty()) {
            JOptionPane.showMessageDialog(this, ret, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void filtroBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroBoxItemStateChanged
        //        if (filtroBox.getSelectedIndex() == 0) {
            //                actualizarListado();
            //            }
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroBoxItemStateChanged

    private void filtroEquiTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroEquiTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroEquiTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dEquipmentControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dEquipmentControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dEquipmentControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dEquipmentControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dEquipmentControl dialog = new dEquipmentControl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CTRL;
    private javax.swing.JComboBox<String> filtroBox;
    private javax.swing.JTextField filtroEquiTxt;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
